###### 配置开启 Spring Boot Bean id 的 Override 机制
spring:
  main:
    allow-bean-definition-overriding: true
###### 配置 Eureka Client 连接 Eureka Server 地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/