drop table if exists emr_summary;
create table emr_summary(
	id varchar(100) not null comment '主键',
	docName varchar(100) default '病历概要' comment '文档标识-名称',
	docCatCode varchar(100) default '01' comment '文档标识-类别代码',
	docOrgName varchar(100) comment '文档标识-管理机构名称',
	docOrgCode varchar(100) comment '文档标识-管理机构组织机构代码（法人代码）',
	docNo varchar(100) comment '文档标识-号码',
	docEffDate timestamp default current_timestamp comment '文档标识-生效日期',
	docExpDate timestamp comment '文档标识-失效日期',
	srvNoCatCode varchar(100) comment '标识号-类别代码',
	srvNo varchar(100) comment '标识号-号码',
	srvNoEffDate date comment '标识号-生效日期',
	srvNoExpDate date comment '标识号-失效日期',
	srvNoOrgName varchar(100) comment '姓名-标识对象',
	srvObject varchar(100) default '患者本人' comment '姓名-标识对象',
	srvObjectCode varchar(100) default '01' comment '姓名-标识对象代码',
	srvName varchar(100) comment '姓名',
	srvPatientCatCode varchar(100) comment '病人类型代码',
	aboBloodCode varchar(100) comment 'ABO血型',
	rhBloodCode varchar(100) comment 'RH血型',
	genderCode varchar(100) comment '性别代码',
	age int(10) comment '年龄（岁）',
	nationality varchar(100) comment '国籍代码',
	ethnicCode varchar(100) comment '民族代码',
	maritalCode varchar(100) comment '婚姻状况类别代码',
	occName varchar(100) comment '职业编码系统名称',
	occCode varchar(100) comment '职业代码',
	birthday date comment '出生日期',
	birthPlace varchar(500) comment '出生地',
	addrUnitName varchar(100) comment '工作单位名称',
	addrCatCode varchar(100) comment '标识地址类别的代码',
	addrProvence varchar(100) comment '地址-省（自治区、直辖市）',
	addrCity varchar(100) comment '地址-市（地区）',
	addrDistrict varchar(100) comment '地址-县（区）',
	addrSubdistrict varchar(100) comment '地址-乡（镇、街道办事处）',
	addrVillage varchar(100) comment '地址-村（街、路、弄等）',
	addrHouseNo varchar(100) comment '地址-门牌号码',
	addrZipCode varchar(100) comment '邮政编码',
	addrDivisionCode varchar(100) comment '行政区划代码',
	eventName varchar(100) comment '卫生事件(动作)名称',
	eventCatCode varchar(100) comment '事件分类代码',
	eventBeginTime timestamp comment '事件开始时间',
	eventEndTime timestamp comment '事件结束时间',
	eventAddress varchar(500) comment '事件发生地点',
	eventPlace varchar(500) comment '事件发生场所',
	eventParticipant varchar(500) comment '事件参与方',
	eventReason varchar(500) comment '事件发生原因',
	eventResult varchar(500) comment '事件结局',
	status varchar(10) not null default 1 comment '系统状态：0-禁用，1-启用',
	createAdmin varchar(100) comment '创建人',
	createTime timestamp not null default current_timestamp comment '创建时间',
	updateAdmin varchar(100) comment '修改人',
	updateTime timestamp not null default current_timestamp on update current_timestamp comment '修改时间',
	primary key(id)
)Engine=InnoDB charset=utf8mb4 comment='病历概要数据信息表';