drop table if exists emr_clinic_rx;
create table emr_clinic_rx(
	id varchar(100) not null comment '主键',
	docName varchar(100) default '西医处方' comment '文档标识-名称',
	docCatCode varchar(100) default '03' comment '文档标识-类别代码',
	docOrgName varchar(100) comment '文档标识-管理机构名称',
	docOrgCode varchar(100) comment '文档标识-管理机构组织机构代码（法人代码）',
	docNo varchar(100) comment '文档标识-号码',
	docEffDate timestamp default current_timestamp comment '文档标识-生效日期',
	docExpDate timestamp comment '文档标识-失效日期',
	srvNoCatCode varchar(100) comment '标识号-类别代码',
	srvNo varchar(100) comment '标识号-号码',
	srvNoEffDate date comment '标识号-生效日期',
	srvNoExpDate date comment '标识号-失效日期',
	srvNoOrgName varchar(100) comment '姓名-标识对象',
	srvObject varchar(100) default '患者本人' comment '姓名-标识对象',
	srvObjectCode varchar(100) default '01' comment '姓名-标识对象代码',
	srvName varchar(100) comment '姓名',
	srvPatientCatCode varchar(100) comment '病人类型代码',
	genderCode varchar(100) comment '性别代码',
	age int(10) comment '年龄（岁）',
	nationality varchar(100) comment '国籍代码',
	ethnicCode varchar(100) comment '民族代码',
	maritalCode varchar(100) comment '婚姻状况类别代码',
	occName varchar(100) comment '职业编码系统名称',
	occCode varchar(100) comment '职业代码',
	birthday date comment '出生日期',
	birthPlace varchar(500) comment '出生地',
	addrUnitName varchar(100) comment '工作单位名称',
	addrCatCode varchar(100) comment '标识地址类别的代码',
	addrProvence varchar(100) comment '地址-省（自治区、直辖市）',
	addrCity varchar(100) comment '地址-市（地区）',
	addrDistrict varchar(100) comment '地址-县（区）',
	addrSubdistrict varchar(100) comment '地址-乡（镇、街道办事处）',
	addrVillage varchar(100) comment '地址-村（街、路、弄等）',
	addrHouseNo varchar(100) comment '地址-门牌号码',
	addrZipCode varchar(100) comment '邮政编码',
	addrDivisionCode varchar(100) comment '行政区划代码',
	orgName varchar(100) comment '机构名称',
	orgCode varchar(100) comment '机构组织机构代码',
	orgCharge varchar(100) comment '机构负责人（法人）',
	orgAddress varchar(500) comment '机构地址',
	orgOfficeName varchar(100) comment '科室名称',
	orgRole varchar(100) comment '机构角色',
	orgRoleCode varchar(100) comment '机构角色代码',
	healthSrvName varchar(100) comment '服务者姓名',
	healthSrvRole varchar(100) comment '服务者职责（角色）',
	healthSrvRoleCode varchar(100) comment '服务者职责（角色）代码',
	healthSrvTechPosition varchar(100) comment '服务者专业技术职务',
	healthSrvBackground varchar(100) comment '服务者学历',
	healthSrvMajor varchar(100) comment '服务者所学专业',
	healthSrvTechPositionRank varchar(100) comment '服务者专业技术职务等级',
	healthSrvPosition varchar(100) comment '服务者职务',
	eventName varchar(100) comment '卫生事件(动作)名称',
	eventCatCode varchar(100) comment '事件分类代码',
	eventBeginTime timestamp comment '事件开始时间',
	eventEndTime timestamp comment '事件结束时间',
	eventAddress varchar(500) comment '事件发生地点',
	eventPlace varchar(500) comment '事件发生场所',
	eventParticipant varchar(500) comment '事件参与方',
	eventReason varchar(500) comment '事件发生原因',
	eventResult varchar(500) comment '事件结局',
	eventObsCat varchar(100) comment '观察-类别',
	eventObsCatCode varchar(100) comment '观察-类别代码',
	eventObsItemName varchar(500) comment '观察项目名称',
	eventObsItemCode varchar(100) comment '观察-项目代码',
	eventObsResult varchar(500) comment '观察-结果描述',
	dxOrgName varchar(100) comment '诊断机构名称',
	dxDate date comment '诊断日期',
	dxCat varchar(100) comment '诊断类别',
	dxCatCode varchar(100) comment '诊断类别代码',
	dxOrderCode varchar(100) comment '诊断顺位（从属关系）代码',
	diseaseName varchar(500) comment '疾病名称',
	diseaseCode varchar(100) comment '疾病代码',
	dxAccording varchar(500) comment '诊断依据',
	dxAccordingCode varchar(100) comment '诊断依据代码',
	txProcessName varchar(500) comment '诊疗过程名称',
	txDescription varchar(500) comment '诊疗过程描述',
	status varchar(10) not null default 1 comment '系统状态：0-禁用，1-启用',
	createAdmin varchar(100) comment '创建人',
	createTime timestamp not null default current_timestamp comment '创建时间',
	updateAdmin varchar(100) comment '修改人',
	updateTime timestamp not null default current_timestamp on update current_timestamp comment '修改时间',
	primary key(id)
)Engine=InnoDB charset=utf8mb4 comment='门(急)诊西医处方数据信息表';